### ISSUE TITLE
使用tag标记agent方式支持存储系统调度

### ISSUE THREAD

**Issue by imotai** [bluebore/galaxy#79]
### 调度系统需要解决以下问题
* 存储系统是有状态应用，运行过程中会产生持久化数据，不能丢失
* 单机运行一个实例
* 需要访问多个磁盘（磁盘管理暂时不支持）

### 调度系统对存储系统要求
* 支持重启，并且能够从持久化数据恢复

#### 用tag标记agent
使用tag标记agent，存储系统调度到特定标签机器上面，凡是这类标签的agent都支持重新启动存储系统，继续复用以前的持久化数据，标签解决存储系统迁移问题。但是目前agent运行task具有workspace概念，workspace里面保存task的包和日志，workspace是没法复用，如果存储系统在workspace做了数据持久化 就没法做迁移。
master需要支持
* 指定机器标记tag
* 在调度器里面加上筛选tag逻辑

实现需要考虑问题，Agent 与 Tag的关系需要持久化存储，用于master恢复时使用.
数据流

#### 当前子卡片
job需要添加一个属性，```one_task_per_host``` #88 
galaxy master 支持 tag标记agent #89 
控制台页面支持 用户标记agent

**Comment by bluebore** [comment]
今天先把下面那个做了吧，调度支持单机运行一个实例。
试试能不能做到天级的开发、cr、发布、上线.

**Comment by imotai** [comment]
ok 我现在在做单个host只运行一个实例
