### ISSUE TITLE
agent压力大的时候，会导致agent无法和master保持heart beat

### ISSUE THREAD

**Issue by imotai** [bluebore/galaxy#95]
如果上述情况，master会认为agent 挂了

**Comment by bluebore** [comment]
agent压力来自于什么，bug？

**Comment by imotai** [comment]
已经确认为是home磁盘IO过高，导致机器假死，上面所有应用均无法正常运行，目前解决方法将应用移至disk2磁盘，可以保证系统不会出现假死，但是应用还是会受影响，所以需要实现IO隔离，才能从根本解决问题
